version: 1.0.{build}
image:
- Ubuntu

environment:
  global:
    USER: sumankhanal
  matrix:
    - RAKU_VERSION: latest
    - RAKU_VERSION: 2023.09

build_script:
  - ps: ./build.ps1

deploy_script:
  - ps: ./deploy.ps1
