version: 1.0.{build}
image:
- Ubuntu
branches:
  only:
    # - main
    - debian-unstable

environment:
  global:
    USER: sumankhanal
  matrix:
    - RAKU_VERSION: latest
    - RAKU_VERSION: 2024.06

build_script:
  - ps: ./build.ps1

deploy_script:
  - ps: ./deploy.ps1
